# site.url
# site.baseurl
url: https://tinnvec.com
baseurl: /

# site.title
title: tinnvec.com

# site.author
author: alex

# blog post permalink
permalink: /blog/:year/:month/:day/:title/

# custom collections
collections:
  projects:

# site.repository
# for site.github https://help.github.com/articles/repository-metadata-on-github-pages/
repository: tinnvec/tinnvec.github.io

gems: [jekyll-youtube]