# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /blog/:year/:month/:day/:title/

# Server
host: 0.0.0.0
# port: 4000
baseurl: ""
url: https://tinnvec.com
encoding: UTF-8

# Social
title: tinnvec.com
description: ""
author: alex

# Custom Vars

# Collections
collections:
  projects:

excerpt_separator: '---'